### ISSUE TITLE
Add the ability to untabify or tabify on open also

### ISSUE THREAD

**Issue by lee-dohm** [lee-dohm/tabs-to-spaces#15]
With a confirmation dialog that can be dismissed forever.

**Comment by lee-dohm** [comment]
This was a silly idea :laughing:

**Comment by tamethecomplex** [comment]
Hi @lee-dohm , question about why this was a silly idea?  I was thinking of implementing this exact feature.

**Comment by lee-dohm** [comment]
Because if you have tabify or untabify on Save turned on, then you can simply click the Save key and it's done. It doesn't really offer much benefit.

**Comment by tamethecomplex** [comment]
Oh, that's true.  What I'm trying to do is view the doc with tabs (displayed as two spaces) but persist the file to disk with 4 spaces instead of tabs.  This is because my team uses 4 space indentation but I want to work with the files as if they were indented with two spaces.  I already did a quick hack to this package to display tabs as two spaces and untabify into 4 spaces.  But I'd like to have this happen automatically between editor and disk without having to manually invoke the commands.  Do you think this feature would be useful to some people?  If so I might make the change along with configuration settings and submit a PR for you to review?

**Comment by lee-dohm** [comment]
I can definitely see how that feature would be useful. That feature is beyond the scope of this package though. This package is designed to keep the in-memory representation and the on-disk representation in sync while making corrections to the file contents. Your feature is essentially to have a completely separate in-memory representation from the on-disk representation (a concept that I [explore more thoroughly in a topic on Discuss](https://discuss.atom.io/t/decoupling-display-format-from-storage-format/7245)). This would exponentially increase the complexity of the package, which I'm not prepared to take on the maintenance of :grinning:

Please feel free to take the code I have here as the basis for your own package though. It sounds like what you have in mind would be a very useful package indeed!

**Comment by tamethecomplex** [comment]
Thanks for offering to let me use your code as a starting point, that was going to be my next question!  It's great you already started a thread on discuss about this exact idea.  I think the degree of ambitiousness for my project for now will be strictly tabs and spaces...but I like your idea about making it wider ranging to a wide variety of style preferences.  After all shouldn't we be all debating important things like our software architecture and not how many spaces there are where?? :)

I'll link to my project back here when I publish it.
