### ISSUE TITLE
Convert 'non-leading' tabs feature?

### ISSUE THREAD

**Issue by halleycarleton** [lee-dohm/tabs-to-spaces#21]
Any chance of a feature being added to allow all tabs, not just leading tabs, to be converted to spaces?

**Comment by lee-dohm** [comment]
I'll leave it as an enhancement, but I probably won't be getting to it soon. If you can add more information around what exactly you expect the behavior to be that will make things easier. Also, I won't be adding this option to the on save behavior as I think that would just be too confusing for most.

**Comment by halleycarleton** [comment]
I'm just looking for something to convert all tabs to spaces. For instance:

```js
		var example 		= 'example';
		var longerExample	= 'example';
```

Here I want the tabs after `var example` to be converted to spaces.

**Comment by albertlyu** [comment]
First of all, really like this project, @lee-dohm. 

I would like to second the request for the ability to convert all tabs to spaces, not just leading tabs. For instance, using @halleycarleton's example in the previous comment...

With spaces highlighted:
![screen shot 2015-03-12 at 9 48 04 am](https://cloud.githubusercontent.com/assets/1390356/6620140/1ca8964e-c89d-11e4-8e04-d0a1b1858a7e.png)

With tabs highlighted:
![screen shot 2015-03-12 at 9 49 22 am](https://cloud.githubusercontent.com/assets/1390356/6620143/20673b96-c89d-11e4-9f4d-94c953c8482a.png)

I would like the above example to have all tabs converted to spaces, like so:
![screen shot 2015-03-12 at 9 48 28 am](https://cloud.githubusercontent.com/assets/1390356/6620148/2451e350-c89d-11e4-8100-8d089572bca4.png)

I think there's great value added by this tabs-to-spaces plugin if this feature was added in. I find that copying code from other text editors into Atom leaves a lot of tabs (and not all of them are four spaces long), for instance, SQL code from SQL editors. The ability to immediately convert all tabs everywhere into spaces would greatly improve productivity, as I spend time having to find-and-replace tabs, and I can't catch all of them that way since tabs are not always four spaces long.

**Comment by halleycarleton** [comment]
+1 @albertlyu 

Thanks for improving on my example. That really displays well what I am talking about. I'm also constantly having to do find & replace when copying code into and out of Atom.

**Comment by Fank** [comment]
+1

**Comment by albertlyu** [comment]
Just saw the commit, thanks @lee-dohm! Next time I need to convert all tabs to spaces, I'll provide some feedback.

**Comment by halleycarleton** [comment]
Thanks for the commit @lee-dohm !
