### ISSUE TITLE
After spaces to tabs (or opposite) can you please also toggle soft tabs?

### ISSUE THREAD

**Issue by ioquatix** [lee-dohm/tabs-to-spaces#25]
This would mean that I don't have to run two commands to get tab indentation on a file that was previously using spaces, and vice versa.

**Comment by albertlyu** [comment]
Related: It appears soft tabs are now disabled with the new release of tabs-to-spaces. When I disable tabs-to-spaces, soft tabs are enabled again. I'd like to be able to have soft tabs on while using tabs-to-spaces to untabify code.

**Comment by lee-dohm** [comment]
@albertlyu I can't reproduce that behavior. I always use soft tabs when I run Atom and I use tabs-to-spaces constantly.

Also, since your complaint is a bug, and not related to this feature request, would you please open a new Issue for it?

**Comment by albertlyu** [comment]
@lee-dohm, I just enabled tabs-to-spaces and tested this again, and soft tabs are working. Not sure what the issue was last time, as I remember distinctly checking to make sure Atom's soft tabs were on, perhaps it was after I used the 'untabify on save' feature, though soft tabs are working now even with that on.

If I run into this behavior again, I'll try to provide with details on how to reproduce it. Otherwise, things look good again on my end.

**Comment by lee-dohm** [comment]
Awesome! I'm glad to hear it @albertlyu :grinning:

**Comment by lee-dohm** [comment]
Did some investigation around this last night. It isn't going to work until atom/atom#3719 is fixed.

**Comment by ioquatix** [comment]
It looks like it's fixed?
