### ISSUE TITLE
Saving not preserve line position

### ISSUE THREAD

**Issue by vaudy** [lee-dohm/tabs-to-spaces#26]
Hi, If the top of the view is on line 35 and I use the plugin untabify, it drop from about 10 lines after a save. At the same time, I lost where I was actually editing.

however, the plugin work's fine!

**Comment by lee-dohm** [comment]
I can't reproduce this issue. Here's what I tried:

1. Open a long file (~150 lines)
1. Tabify it so that there is something to untabify
1. Ensure that untabify on save is enabled
1. Save the file with <kbd>Cmd+S</kbd>

**Expected and Actual:** File did not scroll and cursor did not move

Is there something different you're doing?

**Comment by vaudy** [comment]
yes its my setup, it happen even with a 60 lines file. are you on the latest version of atom?

**Comment by lee-dohm** [comment]
Yes, I'm on the latest version, Atom v0.188.0-010154f on Mac OS X 10.10.2 to be exact. It could be another package you have installed interacting poorly. What packages do you have installed?

**Comment by vaudy** [comment]
highlight-selected
js-format
jshint
tabs-to-spaces

I've try to disabled all of them and it doesn't work.. :/

**Comment by vaudy** [comment]
Atom seem's to not refresh the plugin list base on the state 'disabled/enabled'. I have to restart atom to perform changes. I detect this is jsFormat that did this, sorry for the wrong information..

**Comment by lee-dohm** [comment]
It's quite alright. I'm glad it got figured out :grinning:
