### ISSUE TITLE
Config format change?

### ISSUE THREAD

**Issue by axllent** [lee-dohm/tabs-to-spaces#34]
Please excuse me if I misunderstood the config syntax needed to specify individual filetypes, however it seems Atom is changing the config syntax after restart, and either way I cannot get it to work for individual file types.

I have the `none` as the generic setting, but wish to use `tabify` for some file types (eg: PHP). In my `config.cson` I have:
``` 
"*":
  .... ...
  "tabs-to-spaces": {}
```
So I add the following on a **new** line at the bottom (not indented or a subsection of anything):
```
".source.php":
  "tabs-to-spaces":
    "onSave": "tabify"
```
I save the file, but when saving tabs-to-spaces doesn't do anything. I restart Atom, and then notice that Atom has changed the syntax of the last edit in the `config.cson` to:
```
".php.source":
  "tabs-to-spaces":
    onSave: "tabify"
```
(Note the .source.php -> .php.source).

I'm currently using Atom 1.0.7 on Linux. Either way, it doesn't seem to have any effect and tabs-to-spaces doesn't work. If I change the general setting though to `tabify`, it works ~ however I only want certain file types affected so this isn't an option.

Any advice would be greatly appreciated!

**Comment by lee-dohm** [comment]
Yes, Atom may change the format of the CSON in ways that do not change the meaning of the configuration. None of the transformations you list above are "significant" in that if the configuration worked before the transformation then it will work after the transformation.

I think the heart of your problem is that the scope for PHP is not `.source.php` as you assumed:

<img width="555" alt="screen shot 2015-08-20 at 9 10 41 pm" src="https://cloud.githubusercontent.com/assets/1038121/9401164/fdd6ba40-477f-11e5-9dd9-657c338a7c22.png">

You can find the scope for the language on the settings page for the language package:

1. Start Atom
1. Open the Settings View
1. Click the Packages tab
1. Search for the package you want. In this case `language-php`.
1. Click the background of the package description box to open up the settings for the package
1. Find the scope of the grammar (there can be multiple in one language package, c.f. `language-ruby`)

**Comment by axllent** [comment]
Thank you for the tip! That did it.... I can't say the ordering makes sense, however Atom seems to "correct" it in its own way.

I used `".text.html.php"` which automatically (on reload) got changed to:
```
".html.php.text":
  "tabs-to-spaces":
    onSave: "tabify"
```
But your tip for how to find the scope is gold! I don't recall seeing that anywhere in the docs, maybe you can add it (assuming it's not there)?

Thanks again!

**Comment by lee-dohm** [comment]
I just double-checked and the information is there:

https://atom.io/docs/v1.0.7/using-atom-basic-customization#finding-a-language-s-scope-name

It isn't as step-by-step as my example though :smile:
