### ISSUE TITLE
Follow .editorconfig for guidance on converting to spaces

### ISSUE THREAD

**Issue by chris-erickson** [lee-dohm/tabs-to-spaces#46]
We have some projects that are old and use tabs.  We've established `.editorconfig` files for these to control whitespace properly.  Will this package ever support doing whatever the `.editorconfig` for a given file directs?

**Comment by lee-dohm** [comment]
The [editorconfig package](https://atom.io/packages/editorconfig) should set the indentation settings for the editors that are open. Since my package will follow the indentation settings for whatever editor it is executed upon, by the commutative property it should already respect the `.editorconfig` settings you have.
