### ISSUE TITLE
The change from/to tabs should be put in the undo history

### ISSUE THREAD

**Issue by jogc** [lee-dohm/tabs-to-spaces#64]
tabs-to-spaces 1.0.3
atom 1.20.0

It's counterintuitive and pretty dangerous that you can't undo the changes tabs-to-spaces makes with Ctrl-Z. Also, if there is a selection, it should just operate on that selection, not the whole file.

**Comment by lee-dohm** [comment]
The latest version of tabs-to-spaces is v1.0.5 and the latest stable version of Atom is 1.32.2. Please update to the latest versions of each.

Additionally, I just tested this and you can undo the changes that tabs-to-spaces makes with <kbd>Cmd+Z</kbd> on macOS or <kbd>Ctrl+Z</kbd> on other platforms.

Finally, please file separate issues for separate concerns so that they can be addressed separately.
