### ISSUE TITLE
In text length error

### ISSUE THREAD

**Issue by raczben** [lee-dohm/tabs-to-spaces#65]
The plugin has problems, detecting the length of tab character *in* text (I mean tabs not at the beginning of the line.)

```
foo<--->bar
foo2<-->bar2
foo22<->bar22
```

converted to

```
foo        bar
foo2    bar2
foo22    bar22
```

where <---> means tabs

The plugin should detect the position of the tab, not just replace it constant number of spaces

**Comment by lee-dohm** [comment]
You are correct. This package interprets tabs as a fixed number of spaces, not as tab stops. Since there's no deterministic way to figure out the intention of the author with regard to the function of tabs, this is the best option I have available.

If you can write and maintain an npm module to reliably detect the number of spaces an individual tab character should be, I'd consider employing it to enhance this package.

**Comment by raczben** [comment]
It just a modulo division:

1. Get the tab position (the index from the beginning of the line)
2. Divide by the *editor's tab-length*, and get the remainder.
3. The number of the spaces are equal to the *editor's tab-length* minus the remainder.

**Comment by lee-dohm** [comment]
Then it should be very simple to create an npm module and handle any bug reports that arise from how people's expectations differ from your own.
